#!/bin/bash

if [ "$1" == "c" ];
then
  counts=`qmine | tail -n +6 | awk '{print $10}'`
  parseqmine.py $counts
else
#  qmine | tail -n +6 | awk '{print $10, $4}' | sort -r | uniq -c
#fi

  squeue -h -u $USER -o "%j %T" | sort | uniq -c
fi
